import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Camera, Circle, Hand, MousePointer2, PenLine, Play, Sparkles, Square, Zap } from 'lucide-react';
import { HandLandmarker, FilesetResolver } from '@mediapipe/tasks-vision';
import './styles.css';

const MP_VERSION = '0.10.35';
const WASM_URL = `https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${MP_VERSION}/wasm`;
const MODEL_URL = 'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';
const MODES = { draw:{label:'Draw',icon:PenLine,hint:'Freehand ink'}, shape:{label:'Shape',icon:Sparkles,hint:'Align rough shapes'}, pointer:{label:'Pointer',icon:MousePointer2,hint:'Point anywhere'}, laser:{label:'Laser',icon:Zap,hint:'Highlight briefly'} };
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function angle(a,b,c){const ab={x:a.x-b.x,y:a.y-b.y},cb={x:c.x-b.x,y:c.y-b.y},d=(Math.hypot(ab.x,ab.y)*Math.hypot(cb.x,cb.y))||1;return Math.acos(Math.max(-1,Math.min(1,(ab.x*cb.x+ab.y*cb.y)/d)))*180/Math.PI}
function extended(h,m,p,t){return angle(h[m],h[p],h[t])>132&&dist(h[m],h[t])>dist(h[m],h[p])*1.01}
function gesture(h){if(!h||h.length!==21)return'none';const i=extended(h,5,6,8),m=extended(h,9,10,12),r=extended(h,13,14,16),p=extended(h,17,18,20);if(i&&!m&&!r&&!p)return'draw';if(!i&&!m&&!r&&!p)return'pause';if(i&&m&&r&&p)return'clear';return'none'}
function shape(points){if(points.length<12)return null;const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=maxX-minX,h=maxY-minY,s=points[0],e=points.at(-1),closed=dist(s,e)<Math.max(24,Math.min(w,h)*.4);if(closed&&Math.abs(w-h)/Math.max(w,h)<.25)return{type:'circle',cx:(minX+maxX)/2,cy:(minY+maxY)/2,rx:w/2,ry:h/2};if(closed)return{type:'rectangle',x:minX,y:minY,w,h};return{type:'line',from:s,to:e}}

function App(){
 const video=useRef(null),canvas=useRef(null),tracker=useRef(null),stream=useRef(null),raf=useRef(null),previous=useRef(null),smooth=useRef(null),points=useRef([]),lastFrame=useRef(0),lastSeen=useRef(0),clearAt=useRef(0),trail=useRef([]);
 const[camera,setCamera]=useState(false),[ready,setReady]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('draw'),[g,setG]=useState('none'),[tip,setTip]=useState(null),[aligned,setAligned]=useState('');
 const resize=useCallback(()=>{const c=canvas.current,v=video.current;if(!c||!v)return;const r=v.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.style.width=`${r.width}px`;c.style.height=`${r.height}px`;c.getContext('2d').setTransform(d,0,0,d,0,0)},[]);
 const wipe=useCallback(()=>{const c=canvas.current;if(c)c.getContext('2d').clearRect(0,0,c.clientWidth,c.clientHeight);previous.current=null;smooth.current=null;points.current=[];trail.current=[];setAligned('')},[]);
 const segment=useCallback((a,b)=>{const x=canvas.current?.getContext('2d');if(!x||mode==='pointer')return;const n=Math.max(1,Math.ceil(dist(a,b)/2.5));x.save();x.strokeStyle='#f4f1e8';x.lineWidth=mode==='shape'?5:6;x.lineCap='round';x.lineJoin='round';x.shadowColor='#f4f1e8';x.shadowBlur=mode==='draw'?4:7;x.beginPath();x.moveTo(a.x,a.y);for(let i=1;i<=n;i++){const t=i/n;x.lineTo(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t)}x.stroke();x.restore()},[mode]);
 const laser=useCallback(p=>{const c=canvas.current,x=c?.getContext('2d');if(!x)return;trail.current.push({...p,t:performance.now()});trail.current=trail.current.slice(-30);x.clearRect(0,0,c.clientWidth,c.clientHeight);for(let i=1;i<trail.current.length;i++){const a=trail.current[i-1],b=trail.current[i],alpha=Math.max(0,1-(performance.now()-b.t)/600);x.save();x.globalAlpha=alpha;x.strokeStyle='#e97878';x.shadowColor='#e97878';x.shadowBlur=14;x.lineWidth=3+alpha*4;x.lineCap='round';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();x.restore()}},[]);
 const align=useCallback(()=>{if(mode!=='shape'||points.current.length<12)return;const s=shape(points.current),x=canvas.current?.getContext('2d');if(!s||!x)return;x.save();x.strokeStyle='#d8e6c9';x.lineWidth=5;x.lineCap='round';x.shadowColor='#d8e6c9';x.shadowBlur=8;x.beginPath();if(s.type==='circle')x.ellipse(s.cx,s.cy,s.rx,s.ry,0,0,Math.PI*2);else if(s.type==='rectangle')x.roundRect(s.x,s.y,s.w,s.h,Math.min(16,Math.min(s.w,s.h)*.08));else{x.moveTo(s.from.x,s.from.y);x.lineTo(s.to.x,s.to.y)}x.stroke();x.restore();setAligned(`${s.type} aligned`);points.current=[]},[mode]);
 const init=async delegate=>{const vision=await FilesetResolver.forVisionTasks(WASM_URL);return HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL_URL,delegate},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.22,minHandPresenceConfidence:.22,minTrackingConfidence:.22})};
 const start=async()=>{if(!navigator.mediaDevices?.getUserMedia)return setError('Camera access is not supported by this browser.');if(!window.isSecureContext)return setError('Camera access requires HTTPS.');try{setError('');setLoading(true);const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:30}},audio:false});stream.current=s;video.current.srcObject=s;await video.current.play();setCamera(true);setLoading(false);requestAnimationFrame(resize);try{tracker.current=await init('GPU')}catch{tracker.current=await init('CPU')}setReady(true)}catch(e){setLoading(false);setError(e?.name==='NotAllowedError'?'Camera permission was denied. Allow camera access and try again.':e?.message||'Camera could not start.');stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}};
 const stop=()=>{if(raf.current)cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;tracker.current?.close();tracker.current=null;setCamera(false);setReady(false);setTip(null);setG('none');previous.current=null;smooth.current=null};
 const frame=useCallback(()=>{if(!camera)return;const v=video.current,l=tracker.current,now=performance.now();if(v&&l&&v.readyState>=2&&now-lastFrame.current>=30){lastFrame.current=now;try{const r=l.detectForVideo(v,now),h=r?.landmarks?.[0];if(h){lastSeen.current=now;const c=canvas.current;const raw={x:(1-h[8].x)*c.clientWidth,y:h[8].y*c.clientHeight};const old=smooth.current||raw;const delta=dist(raw,old);const alpha=delta>80?.9:delta>35?.76:.58;const p={x:old.x+(raw.x-old.x)*alpha,y:old.y+(raw.y-old.y)*alpha};smooth.current=p;setTip(p);const state=gesture(h);setG(state);
 // POINTER IS NOW A VISION MODE, NOT A GESTURE MODE: fingertip updates whenever a hand exists.
 if(mode==='pointer'){previous.current=p;return}
 if(state==='clear'){if(!clearAt.current)clearAt.current=now;if(now-clearAt.current>700){clearAt.current=0;wipe()}return}clearAt.current=0;
 if(state==='pause'){if(mode==='shape')align();previous.current=null;return}
 if(state!=='draw')return;
 if(mode==='laser'){laser(p);previous.current=p;return}
 if(previous.current)segment(previous.current,p);previous.current=p;if(mode==='shape')points.current.push(p);
 }else if(now-lastSeen.current>220){setTip(null);setG('none');previous.current=null;smooth.current=null}}catch(e){console.warn('AirCanvas vision frame',e)}}raf.current=requestAnimationFrame(frame)},[camera,mode,segment,laser,align,wipe]);
 useEffect(()=>{if(camera)raf.current=requestAnimationFrame(frame);return()=>raf.current&&cancelAnimationFrame(raf.current)},[camera,frame]);useEffect(()=>{addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[resize]);useEffect(()=>()=>stop(),[]);
 const M=MODES[mode];
 return <main className="site"><header className="nav"><div className="wordmark"><span className="mark">A</span><div><strong>AirCanvas</strong><small>gesture studio / 001</small></div></div><div className="nav-meta"><span className={ready?'engine live':'engine'}><i/>{ready?'VISION LIVE':'VISION OFF'}</span><span>PASSION PROJECT</span></div></header>
 <section className="hero"><div className="hero-copy"><p className="kicker">HUMAN · COMPUTER · INTERACTION</p><h1>Put the idea<br/><em>in the air.</em></h1><p className="lead">Your hand becomes the interface. Draw, point, align shapes or highlight ideas without touching the screen.</p><div className="actions">{!camera?<button className="start" onClick={start} disabled={loading}>{loading?<Circle className="spin" size={16}/>:<Play size={16} fill="currentColor"/>}{loading?'Opening camera':'Open camera'}</button>:<button className="stop" onClick={stop}><Square size={14} fill="currentColor"/> Stop</button>}<span><Hand size={15}/> one hand · no mouse</span></div>{error&&<p className="error">{error}</p>}<div className="hero-promise"><span>☝ DRAW</span><span>◇ ALIGN</span><span>⌖ POINT</span><span>⚡ LASER</span></div></div>
 <div className="hero-camera"><div className="camera-top"><span><i className={camera?'on':''}/>{camera?(ready?'VISION TRACKING LIVE':'STARTING VISION'):'LIVE CAMERA'}</span><span>01 / USP</span></div><div className="surface"><video ref={video} className="video" playsInline muted autoPlay/><canvas ref={canvas} className="canvas"/>{tip&&camera&&<div className={`reticle ${mode==='pointer'||g==='draw'?'active':''}`} style={{left:tip.x,top:tip.y}}><span/></div>}{!camera&&<div className="empty"><div className="empty-icon"><Camera size={23}/></div><strong>See AirCanvas in action.</strong><span>Open camera · raise one finger · move.</span></div>}<div className="surface-label">{camera?`${M.label.toUpperCase()} · ${mode==='pointer'?(tip?'TRACKING':'SEARCHING'):(g==='draw'?'LIVE':g==='pause'?'PAUSED':'READY')}`:'YOUR HAND IS THE CONTROLLER'}</div>{aligned&&<div className="shape-toast">✓ {aligned}</div>}</div><div className="camera-bottom"><span>☝ draw</span><span>✊ pause / align</span><span>🖐 clear</span></div></div></section>
 <section className="instruments"><div><small>02 / CHOOSE YOUR INSTRUMENT</small><h2>One surface.<br/>Four ways to explain.</h2></div><div className="mode-grid">{Object.entries(MODES).map(([key,item])=>{const I=item.icon;return <button key={key} className={mode===key?'active':''} onClick={()=>{setMode(key);previous.current=null;points.current=[];trail.current=[]}}><I size={17}/><b>{item.label}</b><small>{item.hint}</small></button>})}</div></section>
 <section className="build"><div><small>03 / VISION FIRST</small><h2>Camera → landmarks →<br/>finger point.</h2></div><p>For now, the only job is making vision reliable. We are tuning the relationship between the camera frame, MediaPipe landmarks, fingertip coordinates, smoothing and screen space before adding more intelligence.</p></section><footer>Made by - Amar <span>·</span> AirCanvas / passion project 001</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);